# file: roles/nodejs/tasks/main.yml

- include_tasks: dependencies.yml

- include_tasks: source_install.yml
  when: nodejs_install_method == "source"

- include_tasks: package_install.yml
  when: nodejs_install_method == "package"
