# file: roles/nodejs/tasks/install_package.yml

- name: Node.js | Add the nodejs chris-lea repository
  apt_repository: repo=ppa:chris-lea/node.js

- name: Node.js | Make sure latest nodejs is installed
  apt: name=nodejs state=latest update_cache=yes